name: $name
version: $version
main: net.mvndicraft.templateplugin.TemplatePlugin
api-version: '1.21'
authors: [ tlm920 ]
description: Core plugin for minigame management on Mvndicraft
website: mvndicraft.net
