name: $name
version: $version
main: net.mvndicraft.mvndisoundscapes.MvndiSoundscapes
api-version: '1.21'
authors: [ tlm920, ewof ]
description: Core plugin for minigame management on Mvndicraft
website: mvndicraft.net
folia-supported: true
dependencies:
  server:
    SiegeWar:
      load: BEFORE
      required: false
    MvndiBattle:
      load: BEFORE
      required: false
