name: Build and Publish Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      # build
      - name: Build with Gradle Wrapper
        run: ./gradlew build
        env:
          MVNDI_MVN_USER: ${{ secrets.MVNDI_MVN_USER }}
          MVNDI_MVN_KEY: ${{ secrets.MVNDI_MVN_KEY }}
      - name: Publish to Remote
        run: ./gradlew publish
        env:
          MVNDI_MVN_USER: ${{ secrets.MVNDI_MVN_USER }}
          MVNDI_MVN_KEY: ${{ secrets.MVNDI_MVN_KEY }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          token: ${{ github.token }}
          artifacts: build/libs/*.jar
          bodyFile: CHANGELOG.md